services:
  frontend:
    build: .
    container_name: signvault-frontend
    ports:
      - "5173:5173" # Standard Vite port
    networks:
      - signvault-network

networks:
  signvault-network:
    external: true