# 1. Identity & Port
# This is how other services (like 'doc') will find you in the registry
spring.application.name=auth-service
server.port=8081

# 2. Database (Dedicated Auth DB)
# Using 'auth_db' ensures your user data is isolated from document data
spring.data.mongodb.uri=mongodb+srv://supritharpcta_db_user:${MONGO_PASSWORD}@cluster0.hxfpwjc.mongodb.net/auth_db?authSource=admin&retryWrites=true&w=majority

# 3. Security & JWT
# These must match the keys used in your JwtUtils class
bezkoder.app.jwtExpirationMs=86400000
bezkoder.app.jwtCookieName=signvault-jwt
# Update this line in your application.properties
bezkoder.app.jwtSecret=${JWT_SECRET:put_a_long_random_string_here_for_dev_mode}

# 4. Discovery Registry Connection
# This tells the registration module where the 'phonebook' (registry) is located
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

#eureka.client.register-with-eureka=true
#eureka.client.fetch-registry=true
# Optional but recommended: link health check to actuator
eureka.client.healthcheck.enabled=true

# Registry shouldn't register with itself
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disable self-preservation for local development
eureka.server.enable-self-preservation=false

# CORS Configuration
app.frontend.url=http://localhost:5173