server.port=9090
spring.application.name=api-gateway

# 1. Eureka Registry Connection
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# 2. ROUTE 1: Auth Service (RegistrationModule)
spring.cloud.gateway.routes[0].id=auth-service
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
spring.cloud.gateway.routes[0].predicates[0]=Path=/api/auth/**
# Only keep this if your backend controller DOES NOT start with /api/auth
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=0

# 3. ROUTE 2: Doc Service (DocUploadModule)
spring.cloud.gateway.routes[1].id=doc-service
spring.cloud.gateway.routes[1].uri=lb://DOC-SIGNATURE-APP
spring.cloud.gateway.routes[1].predicates[0]=Path=/api/documents/**
# Only keep this if your backend controller DOES NOT start with /api/docs
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=0

# 4. Global CORS Configuration
# Handled here so you can remove @CrossOrigin from your 8081 and 8082 apps
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedOrigins=http://localhost:5173
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedMethods=GET,POST,PUT,DELETE,OPTIONS
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowedHeaders=*
spring.cloud.gateway.globalcors.cors-configurations.[/**].allowCredentials=true

spring.docker.compose.enabled=false

