spring.application.name=registration
# MongoDB Atlas Connection
# Connects to 'auth_db'
spring.data.mongodb.uri=mongodb+srv://supritharpcta_db_user:${MONGO_PASSWORD}@cluster0.hxfpwjc.mongodb.net/auth_db?authSource=admin&retryWrites=true&w=majority
# Optional: To see the queries in your console during development
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
# If you are using a local MongoDB:
# spring.data.mongodb.uri=mongodb://localhost:27017/signvault

# JWT Configuration (matched to your JwtUtils)
bezkoder.app.jwtSecret=${JWT_SECRET}
bezkoder.app.jwtExpirationMs=86400000
bezkoder.app.jwtCookieName=signvault-jwt