# 1. Identity & Port
spring.application.name=doc-signature-app
server.port=8082

# 2. Database
spring.data.mongodb.uri=mongodb+srv://supritharpcta_db_user:${MONGO_PASSWORD}@cluster0.hxfpwjc.mongodb.net/signature_db?retryWrites=true&w=majority
# 3. File Upload Constraints (Translated from your YML)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 4. Discovery Server Connection
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

# 5. Registration Settings
# MUST be true to show up in the Eureka Dashboard
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true

# 6. Health Check & Monitoring
# Links Actuator health to Eureka status
eureka.client.healthcheck.enabled=true
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

